academy = input("enter your academy name: ")
print(academy)
school = input("enter your school you go in to: ")
print(school)
name = input("enter your name: ")
print(name)
lastname = input("enter your lastname: ")
print(lastname)
age = input("enter your age: ")
print(age)